version: '3.8'
services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: airbnb-demo
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: